### ISSUE TITLE
unknown field "fallbackToOd"

### ISSUE THREAD

**Issue by trauts2** [spotinst/weaveworks-eksctl#1]
**What happened?**
A description of actual behavior (with error messages).

$ eksctl create cluster -f cluster.yaml
Error: loading config file "cluster.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "fallbackToOd"

**What you expected to happen?**

**How to reproduce it?**
Include the steps to reproduce the bug

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks-spotinst6
  region: us-east-1
  version: '1.15'
nodeGroups:
  - name: standard-workers
    volumeSize: 16 
    labels: 
      role: workers
    privateNetworking: true
    tags: 
      role: eks-workers
      environment: test
      customer: fh
    spotOcean:
      strategy:
        # Percentage of Spot instances that would spin up from the desired 
        # capacity.
        spotPercentage: 100
        # Allow Ocean to utilize any available reserved instances first before 
        # purchasing Spot instances.
        utilizeReservedInstances: true
        # Launch On-Demand instances in case of no Spot instances available.
        fallbackToOd: true
      autoScaler:
        # Enable the Ocean autoscaler. 
        enabled: true
        # Cooldown period between scaling actions.
        cooldown: 300
        # Spare resource capacity management enabling fast assignment of Pods 
        # without waiting for new resources to launch.
        headrooms:
            # Number of CPUs to allocate. CPUs are denoted in millicores, where 
            # 1000 millicores = 1 vCPU.
          - cpuPerUnit: 2
            # Number of GPUs to allocate.
            gpuPerUnit: 0
            # Amount of memory (MB) to allocate.
            memoryPerUnit: 64
            # Number of units to retain as headroom, where each unit has the 
            # defined CPU and memory.
            numOfUnits: 1
      compute:
        instanceTypes:
          # Instance types allowed in the Ocean cluster. Cannot be configured 
          # if the blacklist is configured.
          whitelist: # OR blacklist
            - c5.large
            - c5.xlarge
            - m5.large
            - m5.xlarge
            - m5a.large
            - m5a.xlarge

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ kubectl version
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by trauts2** [comment]
Note that I get this error when following instructions from https://spot.io/blog/eks-done-right-from-control-plane-to-worker-nodes/

Is there a place where I can find the current schema extensions for this fork?  I like that the original publishes the schema.

**Comment by trauts2** [comment]
Any update on this?  This feature is advertised in the spotinst eksctl writeup but it does not seem to be working.  

I know this group was recently enabled, is it monitored?

**Comment by stevenfeltner** [comment]
@trauts2 it’s `fallbackToOnDemand` and not `fallbackToOd`, see: `https://github.com/spotinst/weaveworks-eksctl/blob/feature-spot-ocean/pkg/apis/eksctl.io/v1alpha5/types.go#L830-L831` 

I will have the blog which references this incorrectly fixed.

**Comment by trauts2** [comment]
Great, thanks Steven.

Also note that the eksctl.io project publishes a schema for their config file.  This fork essentially extends the schema.  It would be very useful if this fork published the schema extensions so that users would be able to identify on their own all of the available config options.
