### ISSUE TITLE
Instructions provided in README are incorrect

### ISSUE THREAD

**Issue by trauts2** [spotinst/weaveworks-eksctl#2]
The blog https://spot.io/blog/eks-done-right-from-control-plane-to-worker-nodes/ does a great job showing how to use this fork.  I think a README update that matched this post would be helpful in showing users how to use the spot enhancements.  Currently these show just vanilla eksctl, which doesn't enable any spot.io behaviors

Neat enhancements btw.  I think this is high value as it really lowers the bar to get setup.

**Comment by liranp** [comment]
You're absolutely right, @trauts2. We're working on documenting our changes, you can find the most recent version [here](https://github.com/spotinst/weaveworks-eksctl/blob/ec342f35204faa77a0b67c93bb60612db027ce00/userdocs/src/usage/spot-ocean-nodegroups.md). We're going to raise a PR to merge our work into the upstream repo, so hopefully this will be available on the official website as well.

**Comment by trauts2** [comment]
Great!  Note however that the syntax shown on the blog, which I also see on the doc you reference here, is not accepted by this fork.  See https://github.com/spotinst/weaveworks-eksctl/issues/1
Steven corrected the blog but I see the same syntax here.

Using the config.yaml from the blog, I am seeing an unexpected / concerning behavior with how elastigroup handles events where nodes it manages are killed under the covers; it never brings the cluster back to a consistent state.  I'll open a separate issue for it later after I have more time to test
